// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: morris.proto

package morris

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BoardSpace int32

const (
	BoardSpace_FREE  BoardSpace = 0
	BoardSpace_WHITE BoardSpace = 1
	BoardSpace_BLACK BoardSpace = 2
)

// Enum value maps for BoardSpace.
var (
	BoardSpace_name = map[int32]string{
		0: "FREE",
		1: "WHITE",
		2: "BLACK",
	}
	BoardSpace_value = map[string]int32{
		"FREE":  0,
		"WHITE": 1,
		"BLACK": 2,
	}
)

func (x BoardSpace) Enum() *BoardSpace {
	p := new(BoardSpace)
	*p = x
	return p
}

func (x BoardSpace) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BoardSpace) Descriptor() protoreflect.EnumDescriptor {
	return file_morris_proto_enumTypes[0].Descriptor()
}

func (BoardSpace) Type() protoreflect.EnumType {
	return &file_morris_proto_enumTypes[0]
}

func (x BoardSpace) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BoardSpace.Descriptor instead.
func (BoardSpace) EnumDescriptor() ([]byte, []int) {
	return file_morris_proto_rawDescGZIP(), []int{0}
}

type Phase int32

const (
	Phase_PLACE Phase = 0
	Phase_MOVE  Phase = 1
	Phase_FLY   Phase = 2
)

// Enum value maps for Phase.
var (
	Phase_name = map[int32]string{
		0: "PLACE",
		1: "MOVE",
		2: "FLY",
	}
	Phase_value = map[string]int32{
		"PLACE": 0,
		"MOVE":  1,
		"FLY":   2,
	}
)

func (x Phase) Enum() *Phase {
	p := new(Phase)
	*p = x
	return p
}

func (x Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_morris_proto_enumTypes[1].Descriptor()
}

func (Phase) Type() protoreflect.EnumType {
	return &file_morris_proto_enumTypes[1]
}

func (x Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Phase.Descriptor instead.
func (Phase) EnumDescriptor() ([]byte, []int) {
	return file_morris_proto_rawDescGZIP(), []int{1}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_morris_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_morris_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_morris_proto_rawDescGZIP(), []int{0}
}

type Move struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From   int32 `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To     int32 `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	Remove int32 `protobuf:"varint,3,opt,name=remove,proto3" json:"remove,omitempty"`
}

func (x *Move) Reset() {
	*x = Move{}
	if protoimpl.UnsafeEnabled {
		mi := &file_morris_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move) ProtoMessage() {}

func (x *Move) ProtoReflect() protoreflect.Message {
	mi := &file_morris_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Move.ProtoReflect.Descriptor instead.
func (*Move) Descriptor() ([]byte, []int) {
	return file_morris_proto_rawDescGZIP(), []int{1}
}

func (x *Move) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *Move) GetTo() int32 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *Move) GetRemove() int32 {
	if x != nil {
		return x.Remove
	}
	return 0
}

type BoardState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Board       []BoardSpace `protobuf:"varint,1,rep,packed,name=board,proto3,enum=BoardSpace" json:"board,omitempty"`
	Turn        BoardSpace   `protobuf:"varint,2,opt,name=turn,proto3,enum=BoardSpace" json:"turn,omitempty"`
	WhitePieces int32        `protobuf:"varint,3,opt,name=whitePieces,proto3" json:"whitePieces,omitempty"`
	BlackPieces int32        `protobuf:"varint,4,opt,name=blackPieces,proto3" json:"blackPieces,omitempty"`
	WhiteGrave  int32        `protobuf:"varint,5,opt,name=whiteGrave,proto3" json:"whiteGrave,omitempty"`
	BlackGrave  int32        `protobuf:"varint,6,opt,name=blackGrave,proto3" json:"blackGrave,omitempty"`
	Phase       Phase        `protobuf:"varint,7,opt,name=phase,proto3,enum=Phase" json:"phase,omitempty"`
}

func (x *BoardState) Reset() {
	*x = BoardState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_morris_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoardState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardState) ProtoMessage() {}

func (x *BoardState) ProtoReflect() protoreflect.Message {
	mi := &file_morris_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardState.ProtoReflect.Descriptor instead.
func (*BoardState) Descriptor() ([]byte, []int) {
	return file_morris_proto_rawDescGZIP(), []int{2}
}

func (x *BoardState) GetBoard() []BoardSpace {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *BoardState) GetTurn() BoardSpace {
	if x != nil {
		return x.Turn
	}
	return BoardSpace_FREE
}

func (x *BoardState) GetWhitePieces() int32 {
	if x != nil {
		return x.WhitePieces
	}
	return 0
}

func (x *BoardState) GetBlackPieces() int32 {
	if x != nil {
		return x.BlackPieces
	}
	return 0
}

func (x *BoardState) GetWhiteGrave() int32 {
	if x != nil {
		return x.WhiteGrave
	}
	return 0
}

func (x *BoardState) GetBlackGrave() int32 {
	if x != nil {
		return x.BlackGrave
	}
	return 0
}

func (x *BoardState) GetPhase() Phase {
	if x != nil {
		return x.Phase
	}
	return Phase_PLACE
}

var File_morris_proto protoreflect.FileDescriptor

var file_morris_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6d, 0x6f, 0x72, 0x72, 0x69, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x07,
	0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x42, 0x0a, 0x04, 0x4d, 0x6f, 0x76, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x66,
	0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x74, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x22, 0xf2, 0x01, 0x0a, 0x0a,
	0x42, 0x6f, 0x61, 0x72, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x21, 0x0a, 0x05, 0x62, 0x6f,
	0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x42, 0x6f, 0x61, 0x72,
	0x64, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x1f, 0x0a,
	0x04, 0x74, 0x75, 0x72, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x42, 0x6f,
	0x61, 0x72, 0x64, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52, 0x04, 0x74, 0x75, 0x72, 0x6e, 0x12, 0x20,
	0x0a, 0x0b, 0x77, 0x68, 0x69, 0x74, 0x65, 0x50, 0x69, 0x65, 0x63, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0b, 0x77, 0x68, 0x69, 0x74, 0x65, 0x50, 0x69, 0x65, 0x63, 0x65, 0x73,
	0x12, 0x20, 0x0a, 0x0b, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x50, 0x69, 0x65, 0x63, 0x65, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x50, 0x69, 0x65, 0x63,
	0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x77, 0x68, 0x69, 0x74, 0x65, 0x47, 0x72, 0x61, 0x76, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x77, 0x68, 0x69, 0x74, 0x65, 0x47, 0x72, 0x61,
	0x76, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x47, 0x72, 0x61, 0x76, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x62, 0x6c, 0x61, 0x63, 0x6b, 0x47, 0x72, 0x61,
	0x76, 0x65, 0x12, 0x1c, 0x0a, 0x05, 0x70, 0x68, 0x61, 0x73, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x06, 0x2e, 0x50, 0x68, 0x61, 0x73, 0x65, 0x52, 0x05, 0x70, 0x68, 0x61, 0x73, 0x65,
	0x2a, 0x2c, 0x0a, 0x0a, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x53, 0x70, 0x61, 0x63, 0x65, 0x12, 0x08,
	0x0a, 0x04, 0x46, 0x52, 0x45, 0x45, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x57, 0x48, 0x49, 0x54,
	0x45, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x42, 0x4c, 0x41, 0x43, 0x4b, 0x10, 0x02, 0x2a, 0x25,
	0x0a, 0x05, 0x50, 0x68, 0x61, 0x73, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x50, 0x4c, 0x41, 0x43, 0x45,
	0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4d, 0x4f, 0x56, 0x45, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03,
	0x46, 0x4c, 0x59, 0x10, 0x02, 0x32, 0x51, 0x0a, 0x06, 0x4d, 0x6f, 0x72, 0x72, 0x69, 0x73, 0x12,
	0x27, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x61, 0x72, 0x64, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x12, 0x06, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0b, 0x2e, 0x42, 0x6f, 0x61, 0x72,
	0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x30, 0x01, 0x12, 0x1e, 0x0a, 0x08, 0x4d, 0x61, 0x6b, 0x65,
	0x4d, 0x6f, 0x76, 0x65, 0x12, 0x05, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x1a, 0x0b, 0x2e, 0x42, 0x6f,
	0x61, 0x72, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x42, 0x6c, 0x75, 0x65, 0x4d, 0x61, 0x6e, 0x67, 0x6f,
	0x31, 0x30, 0x2f, 0x4e, 0x69, 0x6e, 0x65, 0x2d, 0x6d, 0x65, 0x6e, 0x2d, 0x73, 0x2d, 0x6d, 0x6f,
	0x72, 0x72, 0x69, 0x73, 0x2f, 0x6d, 0x6f, 0x72, 0x72, 0x69, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_morris_proto_rawDescOnce sync.Once
	file_morris_proto_rawDescData = file_morris_proto_rawDesc
)

func file_morris_proto_rawDescGZIP() []byte {
	file_morris_proto_rawDescOnce.Do(func() {
		file_morris_proto_rawDescData = protoimpl.X.CompressGZIP(file_morris_proto_rawDescData)
	})
	return file_morris_proto_rawDescData
}

var file_morris_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_morris_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_morris_proto_goTypes = []interface{}{
	(BoardSpace)(0),    // 0: BoardSpace
	(Phase)(0),         // 1: Phase
	(*Empty)(nil),      // 2: Empty
	(*Move)(nil),       // 3: Move
	(*BoardState)(nil), // 4: BoardState
}
var file_morris_proto_depIdxs = []int32{
	0, // 0: BoardState.board:type_name -> BoardSpace
	0, // 1: BoardState.turn:type_name -> BoardSpace
	1, // 2: BoardState.phase:type_name -> Phase
	2, // 3: Morris.GetBoardStream:input_type -> Empty
	3, // 4: Morris.MakeMove:input_type -> Move
	4, // 5: Morris.GetBoardStream:output_type -> BoardState
	4, // 6: Morris.MakeMove:output_type -> BoardState
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_morris_proto_init() }
func file_morris_proto_init() {
	if File_morris_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_morris_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_morris_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Move); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_morris_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoardState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_morris_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_morris_proto_goTypes,
		DependencyIndexes: file_morris_proto_depIdxs,
		EnumInfos:         file_morris_proto_enumTypes,
		MessageInfos:      file_morris_proto_msgTypes,
	}.Build()
	File_morris_proto = out.File
	file_morris_proto_rawDesc = nil
	file_morris_proto_goTypes = nil
	file_morris_proto_depIdxs = nil
}
